name: hf-sync
on:
  release: { types: [published] }
  workflow_dispatch:
jobs:
  sync:
    runs-on: ubuntu-latest   # or [self-hosted, Windows]
    env:
      HF_TOKEN: ${{ secrets.HF_TOKEN }}
      HF_REPO_ID: "idiakhoas/protocolpilot"
      HF_REPO_TYPE: "dataset"
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0, ref: ${{ github.event.release.tag_name || github.ref }} }
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - run: |
          python -m pip install -U pip wheel
          pip install huggingface_hub
      - name: Upload folder to HF
        run: |
          python - << 'PY'
          import os
          from huggingface_hub import HfApi
          api = HfApi(token=os.environ["HF_TOKEN"])
          api.create_repo(repo_id=os.environ["HF_REPO_ID"], repo_type=os.environ["HF_REPO_TYPE"], exist_ok=True)
          api.upload_folder(
              repo_id=os.environ["HF_REPO_ID"], repo_type=os.environ["HF_REPO_TYPE"],
              folder_path=".", path_in_repo="",
              commit_message=f"Sync {os.environ.get('GITHUB_REF_NAME','manual')}",
              ignore_patterns=[".git/*",".github/*","__pycache__/*","*.zip",".venv/*","venv/*"]
          )
          PY
