name: hf-sync

on:
  release:
    types: [published]     # auto-run when a Release is published
  workflow_dispatch:        # allow manual runs from Actions

concurrency: hf-sync-${{ github.ref }}
permissions:
  contents: read

jobs:
  sync:
    runs-on: ubuntu-latest
    env:
      HF_REPO_ID: "idiakhoas/protocolpilot"    # <-- correct dataset name
      HF_REPO_TYPE: "dataset"
      HF_TOKEN: ${{ secrets.HF_TOKEN }}
      UPLOAD_PATH: "."                          # upload repo root

    steps:
      - name: Fail fast if secret missing
        if: env.HF_TOKEN == ''
        run: |
          echo "::error::HF_TOKEN secret is not configured in repo settings."
          exit 1

      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.release.tag_name || github.ref }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install -U pip wheel
          pip install huggingface_hub

      - name: Upload folder to Hugging Face
        run: |
          python - << 'PY'
          import os
          from huggingface_hub import HfApi
          token     = os.environ["HF_TOKEN"]
          repo_id   = os.environ["HF_REPO_ID"]
          repo_type = os.environ.get("HF_REPO_TYPE", "dataset")
          folder    = os.environ.get("UPLOAD_PATH", ".")
          refname   = os.environ.get("GITHUB_REF_NAME") or os.environ.get("GITHUB_SHA","manual")[:7]
          api = HfApi(token=token)
          api.create_repo(repo_id=repo_id, repo_type=repo_type, exist_ok=True)
          api.upload_folder(
              repo_id=repo_id,
              repo_type=repo_type,
              folder_path=folder,
              path_in_repo="",
              commit_message=f"Sync from GitHub ({refname})",
              ignore_patterns=[
                ".git/*",".github/*","**/__pycache__/*",".pytest_cache/*",".mypy_cache/*",
                ".venv/*","venv/*","*.egg-info/*","dist/*","build/*","*.zip",".DS_Store"
              ],
          )
          print("✅ Upload to Hugging Face completed.")
          PY
