name: hf-sync
on:
  release: { types: [published] }    # auto on new release
  workflow_dispatch:                 # allow manual run

jobs:
  sync:
    runs-on: ubuntu-latest
    env:
      HF_TOKEN: ${{ secrets.HF_TOKEN }}
      HF_REPO_ID: "idiakhoas/protocolpilot"   # your dataset
      HF_REPO_TYPE: "dataset"
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }

      - run: |
          python -m pip install -U pip wheel
          pip install huggingface_hub

      - name: Upload folder to HF
        run: |
          python - << 'PY'
          import os
          from huggingface_hub import HfApi
          api = HfApi(token=os.environ["HF_TOKEN"])
          api.create_repo(repo_id=os.environ["HF_REPO_ID"],
                          repo_type=os.environ["HF_REPO_TYPE"], exist_ok=True)
          api.upload_folder(
              repo_id=os.environ["HF_REPO_ID"],
              repo_type=os.environ["HF_REPO_TYPE"],
              folder_path=".",                  # repo root
              path_in_repo="",                  # upload to root of HF repo
              commit_message=f"Sync {os.environ.get('GITHUB_REF_NAME','manual')}",
              ignore_patterns=[
                ".git/*",".github/*","**/__pycache__/*",".pytest_cache/*",".mypy_cache/*",
                ".venv/*","venv/*","*.egg-info/*","*.zip"
              ],
          )
          PY
